#!/bin/bash

for((c = 1; c < 3; c ++))
do
	#fedvag local only
		python main_fedrep.py --alg fedavg --epochs 30 --num_users 5 --shard_per_user 5 --limit_local_output 0 --local_rep_ep 3 --local_only 1 --is_reset_dataset 1 --is_concept_shift 0 --frac 1 --dataset cifar10 --model resnet18

		python main_fedrep.py --alg fedavg --epochs 30 --num_users 5 --shard_per_user 5 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 1 --dataset cifar10 --model resnet18

		python main_fedrep.py --alg fedrep --epochs 30 --num_users 5 --shard_per_user 5 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 1 --dataset cifar10 --model resnet18

		python main_fedpac.py --alg fedrep --epochs 30 --num_users 5 --shard_per_user 5 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 1 --dataset cifar10 --model resnet18

		python main_fedrep_increment2.py --alg fedrep --epochs 10 --num_users 5 --shard_per_user 5 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 1 --dataset cifar10 --model resnet18

done

for((c = 1; c < 3; c ++))
do
	#fedvag local only
		python main_fedrep.py --alg fedavg --epochs 30 --num_users 5 --shard_per_user 2 --limit_local_output 1 --local_rep_ep 3 --local_only 1 --is_reset_dataset 1 --is_concept_shift 0 --frac 1 --dataset cifar10 --model resnet18

		python main_fedrep.py --alg fedavg --epochs 30 --num_users 5 --shard_per_user 2 --limit_local_output 1 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 1 --dataset cifar10 --model resnet18

		python main_fedrep.py --alg fedrep --epochs 30 --num_users 5 --shard_per_user 2 --limit_local_output 1 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 1 --dataset cifar10 --model resnet18

		python main_fedpac.py --alg fedrep --epochs 30 --num_users 5 --shard_per_user 2 --limit_local_output 1 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 1 --dataset cifar10 --model resnet18

		python main_fedrep_increment2.py --alg fedrep --epochs 10 --num_users 5 --shard_per_user 2 --limit_local_output 1 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 1 --dataset cifar10 --model resnet18

done

for((c = 1; c < 3; c ++))
do
	#fedvag local only
		python main_fedrep.py --alg fedavg --epochs 30 --num_users 2 --shard_per_user 5 --limit_local_output 1 --local_rep_ep 3 --local_only 1 --is_reset_dataset 1 --is_concept_shift 0 --frac 1 --dataset cifar10 --model resnet18

		python main_fedrep.py --alg fedavg --epochs 30 --num_users 2 --shard_per_user 5 --limit_local_output 1 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 1 --dataset cifar10 --model resnet18

		python main_fedrep.py --alg fedrep --epochs 30 --num_users 2 --shard_per_user 5 --limit_local_output 1 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 1 --dataset cifar10 --model resnet18

		python main_fedpac.py --alg fedrep --epochs 30 --num_users 2 --shard_per_user 5 --limit_local_output 1 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 1 --dataset cifar10 --model resnet18

		python main_fedrep_increment2.py --alg fedrep --epochs 10 --num_users 2 --shard_per_user 5 --limit_local_output 1 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 1 --dataset cifar10 --model resnet18
done


