#!/bin/bash


for((c = 1; c < 2; c ++))
do


   python main_fedrep.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 1 --is_concept_shift 1 --concept_shift_rate 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1 --data_store_file dict_user_2;

		python main_fedrep.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1 --data_store_file dict_user_2;

		python main_fedpac_k_means.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1 --data_store_file dict_user_2;

		python main_ditto.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1 --data_store_file dict_user_2;

    python main_scaffold.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1 --data_store_file dict_user_2;

done

for((c = 1; c < 2; c ++))
do
		python main_fedrep.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1 --concept_shift_rate 0.2 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1 --data_store_file dict_user_2;

		python main_fedrep.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 0.2 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1 --data_store_file dict_user_2;

		python main_fedpac_k_means.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 0.2 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1 --data_store_file dict_user_2;

		python main_ditto.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 0.2 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1 --data_store_file dict_user_2;

    python main_scaffold.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 0.2 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1 --data_store_file dict_user_2;

done

for((c = 1; c < 2; c ++))
do
		python main_fedrep.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1 --concept_shift_rate 0.4 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1 --data_store_file dict_user_2;

		python main_fedrep.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 0.4 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1 --data_store_file dict_user_2;

		python main_fedpac_k_means.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 0.4 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1 --data_store_file dict_user_2;

		python main_ditto.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 0.4 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1 --data_store_file dict_user_2;

    python main_scaffold.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 0.4 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1 --data_store_file dict_user_2;

done

for((c = 1; c < 2; c ++))
do
		python main_fedrep.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1 --concept_shift_rate 0.6 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1 --data_store_file dict_user_2;

		python main_fedrep.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 0.6 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1 --data_store_file dict_user_2;

		python main_fedpac_k_means.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 0.6 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1 --data_store_file dict_user_2;

		python main_ditto.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 0.6 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1 --data_store_file dict_user_2;

    python main_scaffold.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 0.6 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1 --data_store_file dict_user_2;

done

for((c = 1; c < 2; c ++))
do
		python main_fedrep.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1 --concept_shift_rate 0.8 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1 --data_store_file dict_user_2;

		python main_fedrep.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 0.8 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1 --data_store_file dict_user_2;

		python main_fedpac_k_means.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 0.8 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1 --data_store_file dict_user_2;

		python main_ditto.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 0.8 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1 --data_store_file dict_user_2;

    python main_scaffold.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 0.8 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1 --data_store_file dict_user_2;

done

for((c = 1; c < 2; c ++))
do
		python main_fedrep.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1 --concept_shift_rate 1 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1 --data_store_file dict_user_2;

		python main_fedrep.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 1 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1 --data_store_file dict_user_2;

		python main_fedpac_k_means.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 1 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1 --data_store_file dict_user_2;

		python main_ditto.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 1 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1 --data_store_file dict_user_2;

    python main_scaffold.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 1 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1 --data_store_file dict_user_2;

done





