#!/bin/bash

for((c = 1; c < 2; c ++))
do
	#fedvag local only
		python main_fedrep.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 1 --is_reset_dataset 1 --is_concept_shift 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

		python main_fedrep.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

		python main_fedrep.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

    python main_fedrep.py --alg fedper --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

    python main_fedrep.py --alg lg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

		python main_apfl.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

    python main_scaffold.py --alg scaf --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

    python main_ditto.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

    python main_pfedme.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

    python main_fedpac.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

    python main_fedpac_k_means.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

done


for((c = 1; c < 2; c ++))
do
	#fedvag local only
		python main_fedrep.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 0 --local_rep_ep 3 --local_only 1 --is_reset_dataset 1 --is_concept_shift 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

		python main_fedrep.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

		python main_fedrep.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

    python main_fedrep.py --alg fedper --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

    python main_fedrep.py --alg lg --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

		python main_apfl.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

    python main_scaffold.py --alg scaf --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

    python main_pfedme.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

    python main_ditto.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

    python main_fedpac.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

    python main_fedpac_k_means.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

done

for((c = 1; c < 2; c ++))
do
		python main_fedrep.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 1 --local_rep_ep 3 --local_only 1 --is_reset_dataset 1 --is_concept_shift 1 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

		python main_fedrep.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 1 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

		python main_fedrep.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 1 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

    python main_fedrep.py --alg fedper --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 1 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

    python main_fedrep.py --alg lg --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 1 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

		python main_apfl.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 1 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

    python main_scaffold.py --alg scaf --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 1 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

    python main_pfedme.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 1 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

    python main_ditto.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 1 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

    python main_fedpac_k.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 1 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

    python main_fedpac_k_means.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 1 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1


done







for((c = 1; c < 2; c ++))
do
	#fedvag local only
		python main_fedrep.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 1 --is_reset_dataset 1 --is_concept_shift 0 --frac 0.3 --dataset mnist --model mlp --moment 0.5 --is_reset_model 1

		python main_fedrep.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset mnist --model mlp --moment 0.5 --is_reset_model 1

		python main_fedrep.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset mnist --model mlp --moment 0.5 --is_reset_model 1

    python main_fedrep.py --alg fedper --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset mnist --model mlp --moment 0.5 --is_reset_model 1

    python main_fedrep.py --alg lg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset mnist --model mlp --moment 0.5 --is_reset_model 1

		python main_apfl.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset mnist --model mlp --moment 0.5 --is_reset_model 1

    python main_scaffold.py --alg scaf --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset mnist --model mlp --moment 0.5 --is_reset_model 1

    python main_pfedme.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset mnist --model mlp --moment 0.5 --is_reset_model 1

    python main_ditto.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset mnist --model mlp --moment 0.5 --is_reset_model 1

    python main_fedpac.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset mnist --model mlp --moment 0.5 --is_reset_model 1

    python main_fedpac_k_means.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset mnist --model mlp --moment 0.5 --is_reset_model 1

done

for((c = 1; c < 2; c ++))
do
	#fedvag local only
		python main_fedrep.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 0 --local_rep_ep 3 --local_only 1 --is_reset_dataset 1 --is_concept_shift 0 --frac 0.3 --dataset mnist --model mlp --moment 0.5 --is_reset_model 1

		python main_fedrep.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset mnist --model mlp --moment 0.5 --is_reset_model 1

		python main_fedrep.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset mnist --model mlp --moment 0.5 --is_reset_model 1

    python main_fedrep.py --alg fedper --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset mnist --model mlp --moment 0.5 --is_reset_model 1

    python main_fedrep.py --alg lg --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset mnist --model mlp --moment 0.5 --is_reset_model 1

		python main_apfl.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset mnist --model mlp --moment 0.5 --is_reset_model 1

    python main_scaffold.py --alg scaf --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset mnist --model mlp --moment 0.5 --is_reset_model 1

    python main_pfedme.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset mnist --model mlp --moment 0.5 --is_reset_model 1

    python main_ditto.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset mnist --model mlp --moment 0.5 --is_reset_model 1

    python main_fedpac.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset mnist --model mlp --moment 0.5 --is_reset_model 1

    python main_fedpac_k_means.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset mnist --model mlp --moment 0.5 --is_reset_model 1

done

for((c = 1; c < 3; c ++))
do
		python main_fedrep.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 1 --local_rep_ep 3 --local_only 1 --is_reset_dataset 1 --is_concept_shift 1 --frac 0.3 --dataset mnist --model mlp --moment 0.5 --is_reset_model 1

		python main_fedrep.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 1 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1 --frac 0.3 --dataset mnist --model mlp --moment 0.5 --is_reset_model 1

		python main_fedrep.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 1 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1 --frac 0.3 --dataset mnist --model mlp --moment 0.5 --is_reset_model 1

    python main_fedrep.py --alg fedper --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 1 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1 --frac 0.3 --dataset mnist --model mlp --moment 0.5 --is_reset_model 1

    python main_fedrep.py --alg lg --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 1 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1 --frac 0.3 --dataset mnist --model mlp --moment 0.5 --is_reset_model 1

		python main_apfl.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 1 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1 --frac 0.3 --dataset mnist --model mlp --moment 0.5 --is_reset_model 1

    python main_scaffold.py --alg scaf --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 1 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1 --frac 0.3 --dataset mnist --model mlp --moment 0.5 --is_reset_model 1

    python main_pfedme.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 1 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1 --frac 0.3 --dataset mnist --model mlp --moment 0.5 --is_reset_model 1

    python main_ditto.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 1 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1 --frac 0.3 --dataset mnist --model mlp --moment 0.5 --is_reset_model 1

    python main_fedpac.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 1 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1 --frac 0.3 --dataset mnist --model mlp --moment 0.5 --is_reset_model 1

    python main_fedpac_k_means.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 1 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1 --frac 0.3 --dataset mnist --model mlp --moment 0.5 --is_reset_model 1

done










for((c = 1; c < 2; c ++))
do
	#fedvag local only
		python main_fedrep.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 1 --is_reset_dataset 1 --is_concept_shift 0 --frac 0.3 --dataset cifar100 --model cnn --moment 0.5 --is_reset_model 1

		python main_fedrep.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset cifar100 --model cnn --moment 0.5 --is_reset_model 1

		python main_fedrep.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset cifar100 --model cnn --moment 0.5 --is_reset_model 1

    python main_fedrep.py --alg fedper --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset cifar100 --model cnn --moment 0.5 --is_reset_model 1

    python main_fedrep.py --alg lg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset cifar100 --model cnn --moment 0.5 --is_reset_model 1


		python main_apfl.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset cifar100 --model cnn --moment 0.5 --is_reset_model 1

    python main_scaffold.py --alg scaf --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset cifar100 --model cnn --moment 0.5 --is_reset_model 1

    python main_pfedme.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset cifar100 --model cnn --moment 0.5 --is_reset_model 1

		python main_ditto.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset cifar100 --model cnn --moment 0.5 --is_reset_model 1

    python main_fedpac.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset cifar100 --model cnn --moment 0.5 --is_reset_model 1

    python main_fedpac_k_means.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset cifar100 --model cnn --moment 0.5 --is_reset_model 1

done

for((c = 1; c < 2; c ++))
do
	#fedvag local only
		python main_fedrep.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 0 --local_rep_ep 3 --local_only 1 --is_reset_dataset 1 --is_concept_shift 0 --frac 0.3 --dataset cifar100 --model cnn --moment 0.5 --is_reset_model 1

		python main_fedrep.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset cifar100 --model cnn --moment 0.5 --is_reset_model 1

		python main_fedrep.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset cifar100 --model cnn --moment 0.5 --is_reset_model 1

    python main_fedrep.py --alg fedper --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset cifar100 --model cnn --moment 0.5 --is_reset_model 1

    python main_fedrep.py --alg lg --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset cifar100 --model cnn --moment 0.5 --is_reset_model 1

		python main_apfl.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset cifar100 --model cnn --moment 0.5 --is_reset_model 1

    python main_scaffold.py --alg scaf --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset cifar100 --model cnn --moment 0.5 --is_reset_model 1

    python main_pfedme.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset cifar100 --model cnn --moment 0.5 --is_reset_model 1

    python main_ditto.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset cifar100 --model cnn --moment 0.5 --is_reset_model 1

    python main_fedpac.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset cifar100 --model cnn --moment 0.5 --is_reset_model 1

		python main_fedpac_k_means.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 0.3 --dataset cifar100 --model cnn --moment 0.5 --is_reset_model 1

done

for((c = 1; c < 2; c ++))
do
		python main_fedrep.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 1 --local_rep_ep 3 --local_only 1 --is_reset_dataset 1 --is_concept_shift 1 --frac 0.3 --dataset cifar100 --model cnn --moment 0.5 --is_reset_model 1

		python main_fedrep.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 1 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1 --frac 0.3 --dataset cifar100 --model cnn --moment 0.5 --is_reset_model 1

		python main_fedrep.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 1 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1 --frac 0.3 --dataset cifar100 --model cnn --moment 0.5 --is_reset_model 1

    python main_fedrep.py --alg fedper --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 1 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1 --frac 0.3 --dataset cifar100 --model cnn --moment 0.5 --is_reset_model 1

    python main_fedrep.py --alg lg --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 1 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1 --frac 0.3 --dataset cifar100 --model cnn --moment 0.5 --is_reset_model 1


		python main_apfl.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 1 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1 --frac 0.3 --dataset cifar100 --model cnn --moment 0.5 --is_reset_model 1

    python main_scaffold.py --alg scaf --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 1 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1 --frac 0.3 --dataset cifar100 --model cnn --moment 0.5 --is_reset_model 1

    python main_pfedme.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 1 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1 --frac 0.3 --dataset cifar100 --model cnn --moment 0.5 --is_reset_model 1

    python main_ditto.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 1 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1 --frac 0.3 --dataset cifar100 --model cnn --moment 0.5 --is_reset_model 1

    python main_fedpac.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 1 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1 --frac 0.3 --dataset cifar100 --model cnn --moment 0.5 --is_reset_model 1

    python main_fedpac_k_means.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 3 --limit_local_output 1 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1 --frac 0.3 --dataset cifar100 --model cnn --moment 0.5 --is_reset_model 1

done




for((c = 1; c < 2; c ++))
do


   python main_fedrep.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 1 --is_concept_shift 1 --concept_shift_rate 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

		python main_fedrep.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

		python main_fedpac_k_means.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

		python main_ditto.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

    python main_pfedme.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

done

for((c = 1; c < 2; c ++))
do
		python main_fedrep.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 1 --is_concept_shift 1 --concept_shift_rate 0.2 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

		python main_fedrep.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 0.2 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

		python main_fedpac_k_means.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 0.2 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

		python main_ditto.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 0.2 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

    python main_pfedme.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 0.2 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

done

for((c = 1; c < 2; c ++))
do
		python main_fedrep.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 1 --is_concept_shift 1 --concept_shift_rate 0.4 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

		python main_fedrep.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 0.4 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

		python main_fedpac_k_means.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 0.4 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

		python main_ditto.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 0.4 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

    python main_pfedme.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 0.4 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

done

for((c = 1; c < 2; c ++))
do
		python main_fedrep.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 1 --is_concept_shift 1 --concept_shift_rate 0.6 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

		python main_fedrep.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 0.6 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

		python main_fedpac_k_means.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 0.6 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

		python main_ditto.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 0.6 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

    python main_pfedme.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 0.6 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

done

for((c = 1; c < 2; c ++))
do
		python main_fedrep.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 1 --is_concept_shift 1 --concept_shift_rate 0.8 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

		python main_fedrep.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 0.8 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

		python main_fedpac_k_means.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 0.8 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

		python main_ditto.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 0.8 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

    python main_pfedme.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 10 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 1  --concept_shift_rate 0.8 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

done













for((c = 1; c < 2; c ++))
do
		python main_fedrep.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 3 --nums_per_class 100  --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 1 --is_concept_shift 0 --concept_shift_rate 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

		python main_fedrep.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 3 --nums_per_class 100  --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0  --concept_shift_rate 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

		python main_fedpac_k_means.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 3 --nums_per_class 100   --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0  --concept_shift_rate 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

		python main_ditto.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 3 --nums_per_class 100  --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0  --concept_shift_rate 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

    python main_pfedme.py --alg fedavg --epochs 300 --num_users 20 --shard_per_user 3 --nums_per_class 100 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0  --concept_shift_rate 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

done

for((c = 1; c < 2; c ++))
do
		python main_fedrep.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 3 --nums_per_class 200  --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 1 --is_concept_shift 0 --concept_shift_rate 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

		python main_fedrep.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 3 --nums_per_class 200  --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0  --concept_shift_rate 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

		python main_fedpac_k_means.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 3 --nums_per_class 200   --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0  --concept_shift_rate 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

		python main_ditto.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 3 --nums_per_class 200  --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0  --concept_shift_rate 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

    python main_pfedme.py --alg fedavg --epochs 300 --num_users 20 --shard_per_user 3 --nums_per_class 200 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0  --concept_shift_rate 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

done

for((c = 1; c < 2; c ++))
do
		python main_fedrep.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 3 --nums_per_class 300  --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 1 --is_concept_shift 0 --concept_shift_rate 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

		python main_fedrep.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 3 --nums_per_class 300  --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0  --concept_shift_rate 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

		python main_fedpac_k_means.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 3 --nums_per_class 300   --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0  --concept_shift_rate 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

		python main_ditto.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 3 --nums_per_class 300  --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0  --concept_shift_rate 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

    python main_pfedme.py --alg fedavg --epochs 300 --num_users 20 --shard_per_user 3 --nums_per_class 300 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0  --concept_shift_rate 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

done

for((c = 1; c < 2; c ++))
do
		python main_fedrep.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 3 --nums_per_class 400  --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 1 --is_concept_shift 0 --concept_shift_rate 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

		python main_fedrep.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 3 --nums_per_class 400  --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0  --concept_shift_rate 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

		python main_fedpac_k_means.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 3 --nums_per_class 400   --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0  --concept_shift_rate 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

		python main_ditto.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 3 --nums_per_class 400  --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0  --concept_shift_rate 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

    python main_pfedme.py --alg fedavg --epochs 300 --num_users 20 --shard_per_user 3 --nums_per_class 400 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0  --concept_shift_rate 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

done

for((c = 1; c < 2; c ++))
do
		python main_fedrep.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 3 --nums_per_class 500  --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 1 --is_concept_shift 0 --concept_shift_rate 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

		python main_fedrep.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 3 --nums_per_class 500  --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0  --concept_shift_rate 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

		python main_fedpac_k_means.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 3 --nums_per_class 500   --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0  --concept_shift_rate 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

		python main_ditto.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 3 --nums_per_class 500  --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0  --concept_shift_rate 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

    python main_pfedme.py --alg fedavg --epochs 300 --num_users 20 --shard_per_user 3 --nums_per_class 500 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0  --concept_shift_rate 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

done

for((c = 1; c < 2; c ++))
do
		python main_fedrep.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 3 --nums_per_class 600  --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 1 --is_concept_shift 0 --concept_shift_rate 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

		python main_fedrep.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 3 --nums_per_class 600  --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0  --concept_shift_rate 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

		python main_fedpac_k_means.py --alg fedrep --epochs 100 --num_users 20 --shard_per_user 3 --nums_per_class 600   --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0  --concept_shift_rate 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

		python main_ditto.py --alg fedavg --epochs 100 --num_users 20 --shard_per_user 3 --nums_per_class 600  --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0  --concept_shift_rate 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

    python main_pfedme.py --alg fedavg --epochs 300 --num_users 20 --shard_per_user 3 --nums_per_class 600 --limit_local_output 0 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0  --concept_shift_rate 0 --frac 0.3 --dataset cifar10 --model cnn --moment 0.5 --is_reset_model 1

done












