#!/bin/bash

for((c = 1; c < 4; c ++))
do
	#fedvag local onlycgit gc
		python main_fedrep.py --alg fedavg --epochs 35 --num_users 2 --shard_per_user 5 --limit_local_output 1 --local_rep_ep 3 --local_only 1 --is_reset_dataset 1 --is_concept_shift 0 --frac 1 --dataset cifar10 --model resnet18 --moment 0.5 --is_reset_model 1 --gpu 2

		python main_fedrep.py --alg fedavg --epochs 35 --num_users 2 --shard_per_user 5 --limit_local_output 1 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 1 --dataset cifar10 --model resnet18 --moment 0.5 --is_reset_model 0 --gpu 2

		python main_fedrep.py --alg fedrep --epochs 40 --num_users 2 --shard_per_user 5 --limit_local_output 1 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 1 --dataset cifar10 --model resnet18 --moment 0.5 --is_reset_model 0 --gpu 2

		python main_fedpac.py --alg fedrep --epochs 40 --num_users 2 --shard_per_user 5 --limit_local_output 1 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 1 --dataset cifar10 --model resnet18 --moment 0.5 --is_reset_model 0 --gpu 2

		python main_fedrep_increment2.py --alg fedrep --epochs 20 --num_users 2 --shard_per_user 5 --limit_local_output 1 --local_rep_ep 3 --local_only 0 --is_reset_dataset 0 --is_concept_shift 0 --frac 1 --dataset cifar10 --model resnet18 --moment 0.5 --is_reset_model 0 --gpu 2
done


